In [1]:
import torch 
import numpy as np

# Initializing a Tensor

## Directly from data

In [2]:
data = [
    [1, 2],
    [3, 4]
]

x_data = torch.tensor(data)
print(f"x_data : {x_data}")
print(f"x_data.shape : {x_data.shape}")
print(f"x_data.dim() : {x_data.dim()}")
print(f"x_data.dtype : {x_data.dtype}")


x_data : tensor([[1, 2],
        [3, 4]])
x_data.shape : torch.Size([2, 2])
x_data.dim() : 2
x_data.dtype : torch.int64


### type casting

In [3]:
# typecasting
x_data = x_data.type(torch.float64)
print(f"x_data.dtype : {x_data.dtype}")

x_data.dtype : torch.float64


## From a NumPy array

In [4]:
np_array = np.array(data)
print(f"np_array : {np_array}")
print(f"np_array.dtype : {np_array.dtype}")

x_np = torch.from_numpy(np_array)
print(f"x_np : {x_np}") 
print(f"x_np.dtype : {x_np.dtype}")

np_array : [[1 2]
 [3 4]]
np_array.dtype : int64
x_np : tensor([[1, 2],
        [3, 4]])
x_np.dtype : torch.int64


## From another tensor

In [5]:
x_ones = torch.ones_like(x_data)
print(f"x_ones : {x_ones}")

x_zeros = torch.zeros_like(x_data, dtype=torch.int64)
print(f"x_zeros : {x_zeros}")

x_ones : tensor([[1., 1.],
        [1., 1.]], dtype=torch.float64)
x_zeros : tensor([[0, 0],
        [0, 0]])


## With random or constant values

In [6]:
shape = (2, 3, )
rand_tensor = torch.rand(shape) # Returns a tensor filled with random numbers from a uniform distribution on the interval [0, 1)
print(f"rand_tensor : {rand_tensor}")
print(f"rand_tensor.shape : {rand_tensor.shape}")
print(f"rand_tensor.dim() : {rand_tensor.dim()}")

rand_tensor : tensor([[0.4961, 0.7422, 0.3419],
        [0.8327, 0.0481, 0.7910]])
rand_tensor.shape : torch.Size([2, 3])
rand_tensor.dim() : 2


# Attributes of a Tensor

In [7]:
shape = (3, 4)
tensor = torch.randn(shape)# Returns a tensor filled with random numbers from a normal distribution with mean 0 and variance 1 (also called the standard normal distribution).

print(f"tensor : {tensor}")
print(f"tensor.shape : {tensor.shape}")
print(f"tensor.dim() : {tensor.dim()}")
print(f"tensor.dtype : {tensor.dtype}")
print(f"tensor.device : {tensor.device}")


print("")

print(f"tensor.size() : {tensor.size()}")
print(f"tensor.size(0) : {tensor.size(0)}")
print(f"tensor.size(1) : {tensor.size(1)}")
print(f"tensor.size(-1) : {tensor.size(-1)}")
print(f"tensor.size(-1) : {tensor.size(-2)}")


tensor : tensor([[-0.2411,  0.5289, -1.4285,  0.9778],
        [ 1.0248,  1.1322, -1.5756, -0.3983],
        [ 0.2263,  0.8178,  0.6105, -0.5955]])
tensor.shape : torch.Size([3, 4])
tensor.dim() : 2
tensor.dtype : torch.float32
tensor.device : cpu

tensor.size() : torch.Size([3, 4])
tensor.size(0) : 3
tensor.size(1) : 4
tensor.size(-1) : 4
tensor.size(-1) : 3


# Operations on Tensors

## GPU cuda

In [8]:
print(torch.__version__)
print(f"torch.cuda.is_available() : {torch.cuda.is_available()}")

if torch.cuda.is_available():
    print(f"tensor.to('cpu').device : {tensor.to('cpu').device}")
    print(f"tensor.to('cuda').device : {tensor.to('cuda').device}")

1.12.0
torch.cuda.is_available() : True
tensor.to('cpu').device : cpu


tensor.to('cuda').device : cuda:0


## Indexing and Slicing

In [9]:
tensor = torch.arange(16).reshape(4, 4)
print(f"{tensor}")
print(f"First row : {tensor[0, :]}")
print(f"First column : {tensor[:, 0]}")
print(f"Last column : {tensor[:, -1]}")

tensor[:, 1] = 0
print(f"{tensor}")

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]])
First row : tensor([0, 1, 2, 3])
First column : tensor([ 0,  4,  8, 12])
Last column : tensor([ 3,  7, 11, 15])
tensor([[ 0,  0,  2,  3],
        [ 4,  0,  6,  7],
        [ 8,  0, 10, 11],
        [12,  0, 14, 15]])


In [10]:
t1 = torch.cat([tensor, tensor], dim=0)
t2 = torch.cat([tensor, tensor, tensor], dim=1)

print(f"t1 : {t1}")
print(f"t2 : {t2}")

t1 : tensor([[ 0,  0,  2,  3],
        [ 4,  0,  6,  7],
        [ 8,  0, 10, 11],
        [12,  0, 14, 15],
        [ 0,  0,  2,  3],
        [ 4,  0,  6,  7],
        [ 8,  0, 10, 11],
        [12,  0, 14, 15]])
t2 : tensor([[ 0,  0,  2,  3,  0,  0,  2,  3,  0,  0,  2,  3],
        [ 4,  0,  6,  7,  4,  0,  6,  7,  4,  0,  6,  7],
        [ 8,  0, 10, 11,  8,  0, 10, 11,  8,  0, 10, 11],
        [12,  0, 14, 15, 12,  0, 14, 15, 12,  0, 14, 15]])


## Arithmetic operations

### Matrix Multiplication

In [11]:
tensor = torch.rand(4, 4)
y1 = tensor @ tensor.T # matrix multiplication
y2 = tensor.matmul(tensor.T) # same result as above
y3 = torch.rand_like(y1)
torch.matmul(tensor, tensor.T, out=y3)

print(y1)
print(y2)
print(y3)

tensor([[1.0720, 1.0169, 0.6349, 0.6529],
        [1.0169, 1.0306, 0.7810, 0.6758],
        [0.6349, 0.7810, 0.8962, 0.6898],
        [0.6529, 0.6758, 0.6898, 1.0733]])
tensor([[1.0720, 1.0169, 0.6349, 0.6529],
        [1.0169, 1.0306, 0.7810, 0.6758],
        [0.6349, 0.7810, 0.8962, 0.6898],
        [0.6529, 0.6758, 0.6898, 1.0733]])
tensor([[1.0720, 1.0169, 0.6349, 0.6529],
        [1.0169, 1.0306, 0.7810, 0.6758],
        [0.6349, 0.7810, 0.8962, 0.6898],
        [0.6529, 0.6758, 0.6898, 1.0733]])


### Element-wise product

In [12]:
z1 = tensor * tensor # element-wise multiplication
z2 = tensor.mul(tensor) # same result as above
z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

print(z1)
print(z2)
print(z3)

tensor([[0.0489, 0.6058, 0.3310, 0.0863],
        [0.1209, 0.3422, 0.4064, 0.1612],
        [0.4316, 0.0079, 0.2468, 0.2098],
        [0.7891, 0.2749, 0.0016, 0.0076]])
tensor([[0.0489, 0.6058, 0.3310, 0.0863],
        [0.1209, 0.3422, 0.4064, 0.1612],
        [0.4316, 0.0079, 0.2468, 0.2098],
        [0.7891, 0.2749, 0.0016, 0.0076]])
tensor([[0.0489, 0.6058, 0.3310, 0.0863],
        [0.1209, 0.3422, 0.4064, 0.1612],
        [0.4316, 0.0079, 0.2468, 0.2098],
        [0.7891, 0.2749, 0.0016, 0.0076]])


## Single-element tensors : item()

* If you have a one-element tensor, for example by aggregating all values of a tensor into one value, you can convert it to a Python numerical value using item():

In [13]:
tensor = torch.rand(4, 4)

agg = tensor.sum()
print(agg)

agg_item = agg.item()
print(agg_item, type(agg_item))

tensor(8.5807)
8.58067512512207 <class 'float'>


## In-place operations

* Operations that store the result into the operand are called in-place. They are denoted by a _ suffix. For example: x.copy_(y), x.t_(), will change x.

In [14]:
tensor = torch.ones(4, 4)
tensor[:, 1] = 0
print(tensor)

tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


# Bridge with Numpy

## Tensor to NumPy array

In [18]:
t1 = torch.ones(5)
print(f"t1 : {t1}")

n = t1.numpy()
print(f"n : {n}")

t1 : tensor([1., 1., 1., 1., 1.])
n : [1. 1. 1. 1. 1.]


In [19]:
t1.add_(1)
print(f"t1 : {t1}")  
print(f"n : {n}")  

t1 : tensor([2., 2., 2., 2., 2.])
n : [2. 2. 2. 2. 2.]


## NumPy array to Tensor

In [21]:
n = np.ones(5)
t = torch.from_numpy(n)

print(f"n : {n}")
print(f"t : {t}")

n : [1. 1. 1. 1. 1.]
t : tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [22]:
np.add(n, 1, out=n)
print(f"n : {n}")
print(f"t : {t}")

n : [2. 2. 2. 2. 2.]
t : tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
