# Terminology

* `epoch` : 1 forward and backward pass of ALL training samples
* `batch_size` : the number of training samples in one forward & backward pass
* `# of iterations` : 100 samples, batch_size=20 --> 100 / 20 = 5 iterations for 1 epoch 

In [1]:
import torch
import torchvision
from torch.utils.data import Dataset, DataLoader
import numpy as np
import math

In [2]:
# Manually
class WineDataset(Dataset) : 
    def __init__(self) : 
        # data loading
        xy = np.loadtxt("./datasets/wine.csv", delimiter=",", dtype=np.float32, skiprows=1) # load data, skip 1th row
        self.x = torch.from_numpy(xy[:, 1:])
        self.y = torch.from_numpy(xy[:, [0]]) # (n_sample, 1)
        self.n_samples = xy.shape[0]
        
        
    def __getitem__(self, index) :
        # dataset[0]
        return self.x[index], self.y[index] # return tuple (x[index], y[index])
        
    def __len__(self) :
        # len(dataset)
        return self.n_samples

In [5]:
dataset = WineDataset()
first_data = dataset[0]
features, labels = first_data
print(features, labels)

# [1.4230e+01, 1.7100e+00, 2.4300e+00, 1.5600e+01, 1.2700e+02, 2.8000e+00,
#  3.0600e+00, 2.8000e-01, 2.2900e+00, 5.6400e+00, 1.0400e+00, 3.9200e+00,
#  1.0650e+03] 
# ---> one row

# tensor([1.]) 
# ---> label

tensor([1.4230e+01, 1.7100e+00, 2.4300e+00, 1.5600e+01, 1.2700e+02, 2.8000e+00,
        3.0600e+00, 2.8000e-01, 2.2900e+00, 5.6400e+00, 1.0400e+00, 3.9200e+00,
        1.0650e+03]) tensor([1.])


In [6]:
dataset = WineDataset()
dataloader = DataLoader(dataset=dataset, batch_size=4, shuffle=True, num_workers=2) # num_workers -> loading faster

data_iter = iter(dataloader)
data = data_iter.next()
features, labels = data
print(features, labels) # because of batch size = 4

tensor([[1.3480e+01, 1.6700e+00, 2.6400e+00, 2.2500e+01, 8.9000e+01, 2.6000e+00,
         1.1000e+00, 5.2000e-01, 2.2900e+00, 1.1750e+01, 5.7000e-01, 1.7800e+00,
         6.2000e+02],
        [1.3070e+01, 1.5000e+00, 2.1000e+00, 1.5500e+01, 9.8000e+01, 2.4000e+00,
         2.6400e+00, 2.8000e-01, 1.3700e+00, 3.7000e+00, 1.1800e+00, 2.6900e+00,
         1.0200e+03],
        [1.3580e+01, 1.6600e+00, 2.3600e+00, 1.9100e+01, 1.0600e+02, 2.8600e+00,
         3.1900e+00, 2.2000e-01, 1.9500e+00, 6.9000e+00, 1.0900e+00, 2.8800e+00,
         1.5150e+03],
        [1.4220e+01, 1.7000e+00, 2.3000e+00, 1.6300e+01, 1.1800e+02, 3.2000e+00,
         3.0000e+00, 2.6000e-01, 2.0300e+00, 6.3800e+00, 9.4000e-01, 3.3100e+00,
         9.7000e+02]]) tensor([[3.],
        [1.],
        [1.],
        [1.]])


In [9]:
# training loop
num_epochs = 2
total_samples = len(dataset)
n_iterations = total_samples / 4 # total_sample / batch size
print(total_samples, n_iterations)

for epoch in range(num_epochs) :
    for i, (inputs, labels) in enumerate(dataloader) :
        # forward 
        if (i + 1) % 5 == 0 :
            print(f"epoch {epoch + 1} / {num_epochs}, step {i + 1} / {n_iterations}, inputs {inputs.shape}")
        # backward, update
        
        
torchvision.datasets.MNIST()
# fashion-mnist, cifar, coco, ...        

178 44.5
epoch 1 / 2, step 5 / 44.5, inputs torch.Size([4, 13])
epoch 1 / 2, step 10 / 44.5, inputs torch.Size([4, 13])
epoch 1 / 2, step 15 / 44.5, inputs torch.Size([4, 13])
epoch 1 / 2, step 20 / 44.5, inputs torch.Size([4, 13])
epoch 1 / 2, step 25 / 44.5, inputs torch.Size([4, 13])
epoch 1 / 2, step 30 / 44.5, inputs torch.Size([4, 13])
epoch 1 / 2, step 35 / 44.5, inputs torch.Size([4, 13])
epoch 1 / 2, step 40 / 44.5, inputs torch.Size([4, 13])
epoch 1 / 2, step 45 / 44.5, inputs torch.Size([2, 13])
epoch 2 / 2, step 5 / 44.5, inputs torch.Size([4, 13])
epoch 2 / 2, step 10 / 44.5, inputs torch.Size([4, 13])
epoch 2 / 2, step 15 / 44.5, inputs torch.Size([4, 13])
epoch 2 / 2, step 20 / 44.5, inputs torch.Size([4, 13])
epoch 2 / 2, step 25 / 44.5, inputs torch.Size([4, 13])
epoch 2 / 2, step 30 / 44.5, inputs torch.Size([4, 13])
epoch 2 / 2, step 35 / 44.5, inputs torch.Size([4, 13])
epoch 2 / 2, step 40 / 44.5, inputs torch.Size([4, 13])
epoch 2 / 2, step 45 / 44.5, inputs torch