# Tensor 생성

In [4]:
import torch

x = torch.empty(3) # Rank 1 Tensor, 3
print(x)

x = torch.empty(2, 3) # Rank 2 Tensor, 2 x 3
print(x)

x = torch.empty(2, 2, 2, 3) # Rank 4 Tensor, 2 x 2 x 2 x 3
print(x)

tensor([-6.5979e+37,  4.5754e-41, -6.5979e+37])
tensor([[1.3764e+34, 3.0683e-41, 1.3810e+34],
        [3.0683e-41, 4.2599e-43, 0.0000e+00]])
tensor([[[[-6.5980e+37,  4.5754e-41, -6.5980e+37],
          [ 4.5754e-41,  1.4013e-45,  0.0000e+00]],

         [[ 1.4013e-45,  0.0000e+00,  1.4013e-45],
          [ 0.0000e+00,  0.0000e+00,  0.0000e+00]]],


        [[[ 8.9683e-44,  0.0000e+00,  1.5695e-43],
          [ 0.0000e+00,  1.3790e+34,  3.0683e-41]],

         [[ 2.6540e-09,  1.6706e-07,  1.0633e-05],
          [ 1.0930e-05,  2.1707e-18,  1.6678e+19]]]])


In [9]:
x = torch.zeros(2, 2)
print(x)
print(x.dtype)

x = torch.ones(2, 2, dtype=torch.float16)
print(x)
print(x.dtype)

print(x.size())

tensor([[0., 0.],
        [0., 0.]])
torch.float32
tensor([[1., 1.],
        [1., 1.]], dtype=torch.float16)
torch.float16
torch.Size([2, 2])


In [10]:
x = torch.tensor([2.5, 0.1])
print(x)

tensor([2.5000, 0.1000])


# Tensor Operatoions

## element-wise addition

In [19]:
x = torch.rand(2, 2)
y = torch.rand(2, 2)
print(x)
print(y)

z = x + y # element-wise addition
print(z)

z = torch.add(x, y) # element-wise addition
print(z)

y.add_(x) # in-place addition. PyTorch에서 모든 underbar는 in-place를 의미.
print(y) 

tensor([[0.0416, 0.7575],
        [0.7350, 0.1557]])
tensor([[0.4163, 0.0382],
        [0.5382, 0.0180]])
tensor([[0.4579, 0.7957],
        [1.2732, 0.1736]])
tensor([[0.4579, 0.7957],
        [1.2732, 0.1736]])
tensor([[0.4579, 0.7957],
        [1.2732, 0.1736]])


## element-wise substraction

In [23]:
x = torch.rand(2, 2)
y = torch.rand(2, 2)
print(x)
print(y)

z = x - y # element-wise substraction
print(z)

z = torch.sub(x, y) # element-wise substraction
print(z)

x.sub_(y) # in-place substraction. PyTorch에서 모든 underbar는 in-place를 의미.
print(x) 

tensor([[0.4340, 0.9046],
        [0.2238, 0.4649]])
tensor([[0.0986, 0.7191],
        [0.0016, 0.7388]])
tensor([[ 0.3354,  0.1855],
        [ 0.2222, -0.2740]])
tensor([[ 0.3354,  0.1855],
        [ 0.2222, -0.2740]])
tensor([[ 0.3354,  0.1855],
        [ 0.2222, -0.2740]])


## element-wise multiplication

In [29]:
x = torch.rand(2, 2)
y = torch.rand(2, 2)
print(x)
print(y)

z = x * y # element-wise multiplication
print(z)

z = torch.mul(x, y) # element-wise multiplication
print(z)

z = torch.multiply(x, y) # element-wise multiplication
print(z)

x.mul_(y) # in-place multiplication. PyTorch에서 모든 underbar는 in-place를 의미.
print(x) 

tensor([[0.6951, 0.9090],
        [0.2309, 0.8292]])
tensor([[0.2746, 0.7299],
        [0.3157, 0.8014]])
tensor([[0.1909, 0.6635],
        [0.0729, 0.6646]])
tensor([[0.1909, 0.6635],
        [0.0729, 0.6646]])
tensor([[0.1909, 0.6635],
        [0.0729, 0.6646]])
tensor([[0.1909, 0.6635],
        [0.0729, 0.6646]])


## element-wise division

In [28]:
x = torch.rand(2, 2)
y = torch.rand(2, 2)
print(x)
print(y)

z = x / y # element-wise multiplication
print(z)

z = torch.div(x, y) # element-wise multiplication
print(z)

x.div_(y) # in-place multiplication. PyTorch에서 모든 underbar는 in-place를 의미.
print(x) 

tensor([[0.9828, 0.2628],
        [0.8056, 0.8566]])
tensor([[0.9799, 0.2575],
        [0.9965, 0.5600]])
tensor([[1.0029, 1.0209],
        [0.8085, 1.5296]])
tensor([[1.0029, 1.0209],
        [0.8085, 1.5296]])
tensor([[1.0029, 1.0209],
        [0.8085, 1.5296]])


# Slice Operations

In [35]:
x = torch.rand(5, 3)
print(x)

print(x[:, 0]) # all rows, column 0
print(x[1, :]) # row 1, all columns
print(x[1, 1]) # row 1, column 1
print(x[1, 1].item()) # actual value (element가 딱 하나 있는 tensor에서만 사용 가능)

tensor([[0.9947, 0.3079, 0.3668],
        [0.9226, 0.6017, 0.2594],
        [0.1888, 0.5213, 0.1577],
        [0.9080, 0.4297, 0.7105],
        [0.7422, 0.7178, 0.7640]])
tensor([0.9947, 0.9226, 0.1888, 0.9080, 0.7422])
tensor([0.9226, 0.6017, 0.2594])
tensor(0.6017)
0.6016807556152344


# View Operations(reshape)

In [46]:
x = torch.rand(4, 4)
print(x)
y = x.view(16) # reshape
print(y)
print(y.shape)

y = x.view(1, 16) # reshape
print(y)
print(y.shape)

y = x.view(2, 2, 4) # reshape
print(y)
print(y.shape)

y = x.view(-1)
print(y)
print(y.shape)

y = x.view(-1, 8) # -1 : automatically infer the number of rows
print(y)
print(y.shape)

tensor([[0.7841, 0.2714, 0.9357, 0.6280],
        [0.9764, 0.0857, 0.8134, 0.2502],
        [0.5157, 0.0941, 0.7687, 0.0265],
        [0.1741, 0.7468, 0.8573, 0.4340]])
tensor([0.7841, 0.2714, 0.9357, 0.6280, 0.9764, 0.0857, 0.8134, 0.2502, 0.5157,
        0.0941, 0.7687, 0.0265, 0.1741, 0.7468, 0.8573, 0.4340])
torch.Size([16])
tensor([[0.7841, 0.2714, 0.9357, 0.6280, 0.9764, 0.0857, 0.8134, 0.2502, 0.5157,
         0.0941, 0.7687, 0.0265, 0.1741, 0.7468, 0.8573, 0.4340]])
torch.Size([1, 16])
tensor([[[0.7841, 0.2714, 0.9357, 0.6280],
         [0.9764, 0.0857, 0.8134, 0.2502]],

        [[0.5157, 0.0941, 0.7687, 0.0265],
         [0.1741, 0.7468, 0.8573, 0.4340]]])
torch.Size([2, 2, 4])
tensor([0.7841, 0.2714, 0.9357, 0.6280, 0.9764, 0.0857, 0.8134, 0.2502, 0.5157,
        0.0941, 0.7687, 0.0265, 0.1741, 0.7468, 0.8573, 0.4340])
torch.Size([16])
tensor([[0.7841, 0.2714, 0.9357, 0.6280, 0.9764, 0.0857, 0.8134, 0.2502],
        [0.5157, 0.0941, 0.7687, 0.0265, 0.1741, 0.7468, 0.8573, 0.

# Converting NumPy to tensor

In [52]:
import torch
import numpy as np

a = torch.ones(5)
print(a)
print(type(a)) # torch.Tensor

b = a.numpy()
print(b)
print(type(b)) # numpy.ndarray


# ! Tensor가 CPU에 있다면, a와 b는 같은 memory allocation을 공유 !
a.add_(1)
print(a) # 
print(b) # b에도 add_(1) 연산이 적용되었음.

tensor([1., 1., 1., 1., 1.])
<class 'torch.Tensor'>
[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [55]:
a = np.ones(5)
print(a)

b = torch.from_numpy(a)
print(b)

a += 1 # numpy array에 element-wise 1 addition
print(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


# CUDA and How to create tensor on GPU

In [60]:
if torch.cuda.is_available():
    device = torch.device("cuda") # CUDA device object
    x = torch.ones(5, device=device) # directly create a tensor on GPU
    print(x)
    
    y = torch.ones(5) # create a tensor on CPU
    y = y.to(device) # move tensor to GPU
    print(y)
    
    z = x + y # add two tensors on GPU
    # z.numpy() # error!! numpy tensor는 CPU에서만 동작함.
    
    z = z.to("cpu") # move tensor to CPU
    z.numpy() # z는 이제 CPU에 있으므로 numpy() 사용 가능
    print(z)
    

tensor([1., 1., 1., 1., 1.], device='cuda:0')
tensor([1., 1., 1., 1., 1.], device='cuda:0')
tensor([2., 2., 2., 2., 2.])
